arrowParens: "always" # default
bracketSameLine: false # default
bracketSpacing: true # default
embeddedLanguageFormatting: "auto" # default
endOfLine: "lf" # default
filepath: "" # default
htmlWhitespaceSensitivity: "css" # default
insertPragma: false # default
jsxBracketSameLine: false # default
jsxSingleQuote: false # default
parser: "" # default
printWidth: 80 # Default
proseWrap: "preserve" # default
quoteProps: "as-needed" # default
rangeEnd: Infinity # default
rangeStart: 0 # default
requirePragma: false # default
semi: true # default
singleAttributePerLine: "false" # default
singleQuote: false # default
tabWidth: 2 # default
trailingComma: "es5" # default
useTabs: false # default
vueIndentScriptAndStyle: false # default
