name: Run Javascript Tests

on:
  pull_request:
    branches: [main]

jobs:
  all:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install
        run: npm install
      - name: CI
        run: npm ci
        env:
          CI: true
